name: Deploy React App to S3

on:
  push:
    branches:
      - main  # Cambia si tu rama principal es diferente

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.11.0
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: mi-container-admin  # Cambia esto por el nombre real de tu bucket
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1                # Cambia si tu bucket está en otra región
          SOURCE_DIR: build
